talenthub/talenthub/projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.projects, name="projects"),
    path('project/<slug:project_slug>/', views.project, name="project"),
    path('tag/<slug:tag_slug>', views.projects_by_tag, name="tag"),
    path('create-project/', views.createProject, name="create-project"),
    path('update-project/<str:pk>', views.updateProject, name="update-project"),
    path('delete-project/<str:pk>', views.deleteProject, name="delete-project"),
]

talenthub/talenthub/talenthub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
]

talenthub/talenthub/projects/models.py
from django.db import models
import uuid
# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

class Project(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag,blank=True)
    total_voter = models.IntegerField(default=0, null=True, blank=True)
    votes_radio = models.IntegerField(default=0, null=True, blank=True)
    demo_link = models.CharField(max_length=500, null=True, blank=True)
    sourse_link = models.CharField(max_length=500, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    def __str__(self):
        return self.title

class Review(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    review_text = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.value

talenthub/talenthub/projects/forms.py
from django.forms import ModelForm
from .models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        # fields = ['title', 'slug', 'tags', 'description', 'demo_link', 'source_link']

talenthub/talenthub/projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Project, Tag
from .forms import ProjectForm


# Create your views here.
def projects(request):
    projects = Project.objects.all()
    context = {'projects': projects}
    return render(request, 'projects/projects.html', context)


def project(request, project_slug):
    project = Project.objects.get(slug=project_slug)
    tags = project.tags.all()
    return render(request, 'projects/single-project.html', {'project': project})


def createProject(request):
    form = ProjectForm()
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('projects')

def updateProject(request, pk):
    project = Project.objects.get(id=pk)
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('project')
    context = {'form': form}
    return render(request, 'projects/project_form.html', context)


def deleteProject(request, pk):
    project = Project.objects.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('projects')
    context = {'object': project}
    return render(request, 'projects/delete.html')

def projects_by_tag(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    projects = Project.objects.filter(tags__in=[tag])
    context = {
        "projects": projects
    }

    return render(request, "projects/projects.html", context)

talenthub/talenthub/projects/templates/projects.html
<!DOCTYPE html>
<html>
<head>
    <title>Template for project output</title>
</head>
<body>
<h2>All projects will be here</h2>
{% for project in projects %}
<p>Project number: #{{project.id}} </p>
<h3>Project name: <a href="{% utl 'project' project.id %}">{{project.title }}</a></h3>
<em>{{ project.description }}</em>
{% endfor}
</body>
</html>

talenthub/talenthub/projects/templates/projects/delete.html
{% block content %}
<form action="", method="POST">
    {% csrf_token %}
    <p>Sind Sie sicher, dass Sie löschen möchten "{{ object }}"?</p>
    <a href="{% url 'projects' %}">Löschung</a>
    <input type="submit" name="" value="Löschung bestätigen">
</form>
{% endblock %}

talenthub/talenthub/projects/templates/projects/project_form.html
{% extends 'base.html' %}
{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <a class="backButton" href="{% utl 'account' %}"><i class="im im-angle-left"></i> </a>
        <br>

        <form class="form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form %}
            <div class="form_field">
                <label for="formInput#text">{{ field.label }}</label>
                {{field}}
            </div>
            {% endfor %}

            <div class="form_field">
                 {% for tag in project.tags.all %}
                 <div class="project-tag tag tag--pill tag==main" data-tag="{tag.id}}"
                      data-project="{{project.id}}">{{ tag.name }} &#215;</div>
                {% endfor %}

            </div>

            <div class="form_field">
                <label for="formInput#text">Tags</label>
                <textarea class="input" name="newtags" placeholder="Tags hinzufügen"></textarea>
            </div>
            <input class="btn btn--sub btn--lg  my-md" type="submit" value="Sparen" />
        </form>
    </div>
</main>

talenthub/talenthub/projects/templates/projects/projects.html
{% extends 'base.html' %}
{% block content %}

<main class="projects">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>Suche nach <span> Projekten</span></h2>
            </div>

            <div class="hero-section__search">
                <form id='searchForm' class="form" action="{% url 'projects' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Suche nach Projekten</label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="Suche mit Name/Projektbeschreibung" value="{{ search_query }}" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Suchen" />
                </form>
            </div>
        </div>
    </section>
    <section class="projectsList">
        <div class="container">
            <div class="grid grid--three">

                {% for project in projects %}
                <div class="column">
                    <div class="card project">
                        <a href="{% url 'project' project.slug %}" class="project">
                            <img class="project__thumbnail" src="{{ project.imageURL }}" alt="project thumbnail" />
                            <div class="card__body">
                                <h3 class="project__title">{{ project.title }}</h3>
                                <p><a class="project__author" href="#">Developer:
                                        {{ project.owner.name }}</a>
                                </p>
                                <p class="project--rating">
                                    <span style="font-weight: bold;">positives Feedback:</span>  {{ project.votes_ratio }}%
                                </p>
                                 <p class="project--rating">
                                    <span style="font-weight: bold;">Gesamtbewertungen:</span> {{ project.total_votes }}
                                </p>                               
                                <div class="project__tags">
                                    {% for tag in project.tags.all %}
                                    <a href="{% url 'tag' tag.slug %}" class="tag tag--pill tag--main">{{tag}}</a>

                                    {% endfor %}

                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
</main>

{% endblock %}

talenthub/talenthub/projects/templates/projects/single-project.htm
{% extends 'base.html' %}

{% block content %}

<main class="singleProject my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <h3 class="singleProject__subtitle">Plattform und Stapel</h3>
                <div class="singleProject__toolStack">
                {% for tag in project.tags.all %}
                <a href="{% url 'tag' tag.slug %}" class="tag tag--pill tag--sub tag--lg">{{tag}}</a>
                {% endfor %}               
                </div>

                {% if project.source_link %}
                <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i
                        class="im im-external-link"></i>Quellcode auf GitHub
                </a>
                {% endif %}

                {% if project.demo_link %}
                <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i
                        class="im im-external-link"></i>Demo-Site

                </a>
                {% endif %}

            </div>
            <div class="column column--2of3">
                <img class="singleProject__preview" src="{{ project.imageURL }}" alt="portfolio thumbnail" />
                <a href="#"
                    class="singleProject__developer">{{ project.owner.name }}</a>
                <h2 class="singleProject__title">{{ project.title }}</h2>
                <h3 class="singleProject__subtitle">Projekt Information</h3>
                <div class="singleProject__info">
                    {{ project.description }}
                </div>
                <div class="comments">
                    <h3 class="singleProject__subtitle">Bewertungen und Rezensionen</h3>
                    <h5 class="project--rating">
                    Prozentsatz positiver Bewertungen: {{project.votes_ratio}}
                    </h5>
                    <h5 class="project--rating">
                    Gesamtbewertungen: {{project.total_votes}}
                    </h5>
                    {% if request.user.profile.id in project.reviewers %}
                    <p>Sie haben bereits eine Rezension zu diesem Projekt geschrieben</p>

                    {% elif request.user.profile == project.owner %}
                    <p>Sie können kein separates Projekt erstellen</p>

                    {% elif request.user.is_authenticated %}
                    <form class="form" action="{% url 'project' project.id %}" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#textarea">{{ field.label }}</label>
                            {{field}}
                        </div>
                        {% endfor %}
                        <input class="btn btn--sub btn--lg" type="submit" value="Bewertung hinzufügen" />
                    </form>
                    {% else %}
                    <a href="{% url 'login' %}?next={{ request.path }}">Melden Sie sich an, um eine Bewertung abzugeben</a>
                    {% endif %}

                    <div class="commentList">
                        {% for review in project.review_set.all %}
                        {% if review.body %}
                        <div class="comment">
                            <a href="{% url 'user-profile' review.owner.id  %}">
                                <img class="avatar avatar--md" src="{{ review.owner.profile_image.url }}" alt="user" />
                            </a>


                            <div class="comment__details">
                                <a href="{% url 'user-profile' review.owner.id  %}"
                                    class="comment__author">{{ review.owner.name }}</a>
                                <p class="comment__info">{{ review.body|linebreaksbr }}</p>
                            </div>

                        </div>
                        {% endif %}
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

talenthub/talenthub/projects/templates/single-project.htm
<!DOCTYPE html>
<html>
<head>
    <title>Vorlage für ein einzelnes Project.</title>
</head>
<body>
<h1>Detaillierte Informationen zum Project</h1>
<h3>Project #{{ project.id }}</h3>
<p>{{project.title }}</p>
<br>
<em>{{ project.description }}</em>
</body>
</html>

talenthub/talenthub/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}" /">
    <title>TalentHub - Finden Sie Ihren Entwickler </title>
</head>

<body>
{% include 'navbar.html' %}

{% if massages %}

{% for massage in massages %}
<div class="alert alert--{{massage.tag }}">
    <p class="alert_massage">{{massage}}</p>
    <button class="alert_close">Schließen</button>
</div>
 {% endfor %}

{% endif %}

 {% block content %}

{% endblock content %}

<div>
    <footer class="site-footer">
        <div class="footer-content">
            <h3>TalentHub</h3>
            <p>Eine Plattform, auf der jeder Personalvermittler seinen eigenen Entwickler finden kann.</p>
            <ul class="socials">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-telegram"></i></a></li>
                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
            </ul>
        </div>
        <div class="footer-bottom">
            <p>Alle Rechte vorbehalten &copy; <a href="#">TalentHub</a> </p>
             <div class="footer-menu">
                      <ul class="f-menu">
                        <li><a href="">Hauptseite</a></li>
                        <li><a href="">über das Projekt</a></li>
                        <li><a href="">Kontakte</a></li>
                          <li><a href="">Blog</a></li>
                      </ul>
             </div>

        </div>
    </footer>
</div>
</body>
<script src="{% static 'uikit/app.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</html>

talenthub/talenthub/templates/navbar.html
{% load static %}

<header class="header">
    <div class="container container--narrow">
        <a href="{% url 'projects' %}"><span class="header__logo">Talent<i class="fa fa-search"></i>Hub</span></a>
        <nav class="header__nav">
            <input type="checkbox" id="responsive-menu" />
            <label for="responsive-menu" class="toggle-menu">
                <span>Menü</span>
                <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
                <li class="header__menuItem"><a href="#">Developers</a></li>
                <li class="header__menuItem"><a href="#">Projekte</a></li>



                {% if request.user.is_authenticated %}
                <li class="header__menuItem"><a href="#">Mitteilungen</a></li>
                <li class="header__menuItem"><a href="#">Mein Benutzerkonto</a></li>
                <li class="header__menuItem"><a href="#" class="btn btn--sub">Rausgehen</a></li>
                {% else %}
                <li class="header__menuItem"><a href="#" class="btn btn--sub">Eintreten/Anmelden</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>